#include "tss.h"


tss tsss[TSS_COUNT] = {
	(tss) { // Inicializada toda en 0
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short)  0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
			(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0
	},
	(tss) { // Inicializada toda en 0
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short)  0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0
	},
	
	
};
